# Generated by Django 2.2.3 on 2021-04-07 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20210407_1908'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('special_status', 'Can read all tests')]},
        ),
    ]
